build:
  environment:
    python: 3.6
  nodes:
    analysis:
      project_setup:
        override:
          - pip install pipenv
          - pipenv install --dev
      tests:
        override:
          -
            command: pylint-run
            use_website_config: true
          - py-scrutinizer-run
    tests:
      project_setup:
        override:
          - pip install pipenv
          - pipenv install --dev
      tests:
        override:
          -
            command: pipenv run nosetests --with-coverage --cover-package=paytext --cover-min-percentage=100
            coverage:
              file: '.coverage'
          - cp pyre-check.sh.dist pyre-check.sh && ./pyre-check.sh
build_failure_conditions:
  - 'issues.exists'
  - 'elements.rating(< A).exists'
checks:
  python:
    classes_valid_slots: true
    code_rating: true
    duplicate_code: true
