checks:
  python:
    classes_valid_slots: true
    code_rating: true
    duplicate_code: true
build:
nodes:
  analysis:
    tests:
      override:
        -
          command: pylint-run
          use_website_config: true
        - py-scrutinizer-run
  test:
    tests:
      override:
        - nosetests
