checks:
  python:
    classes_valid_slots: true
    code_rating: true
    duplicate_code: true
build:
  environment:
    python: 3.6
  nodes:
    analysis:
      tests:
        override:
          -
            command: pylint-run
            use_website_config: true
          - py-scrutinizer-run
    test:
      tests:
        project_setup:
          - pip install pipenv
          - pipenv install --dev
          - pipenv shell
        override:
          - nosetests
